version: 2
updates:
  - package-ecosystem: gomod
    directory: /governance
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      go-mod:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /console
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /governance
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      docker-governance:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /console
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      docker-console:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
