{{- if .Values.redis.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.redis.serviceName" . }}
  labels:
    {{- include "nexus.redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "nexus.redis.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus.fullname" . }}-redis
  labels:
    {{- include "nexus.redis.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nexus.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus.redis.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.redis.internal.securityContext | nindent 8 }}
      terminationGracePeriodSeconds: 15
      containers:
        - name: redis
          image: "{{ .Values.redis.internal.image.repository }}:{{ .Values.redis.internal.image.tag }}"
          imagePullPolicy: {{ .Values.redis.internal.image.pullPolicy }}
          command: ["redis-server", "--appendonly", "yes", "--save", "60", "1"]
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            {{- toYaml .Values.redis.internal.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.redis.internal.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
{{- end }}
