apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus.secretName" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
