// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"data-plane/cmd/config"
	"data-plane/internal/a2a"
	"data-plane/internal/actionoverrides"
	"data-plane/internal/admin"
	"data-plane/internal/approval"
	"data-plane/internal/audit"
	"data-plane/internal/egress"
	"data-plane/internal/gateway"
	"data-plane/internal/gateway/executor/telemetry"
	"data-plane/internal/identity"
	"data-plane/internal/mcp"
	"data-plane/internal/org"
	"data-plane/internal/policy"
	"data-plane/internal/secrets"
	"data-plane/internal/tool"
	"data-plane/internal/usagemetering"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*App, func(), error) {
	dbConfig := ProvideDBConfig(cfg)
	serviceConfig := ProvideServiceConfig(cfg)
	logger := NewLogger(serviceConfig)
	gormConfig := NewGormConfig(logger)
	db, cleanup, err := NewDB(dbConfig, gormConfig)
	if err != nil {
		return nil, nil, err
	}
	httpServerConfig := ProvideHTTPServerConfig(cfg)
	repository := org.NewRepository(db)
	usecases := org.NewUsecases(repository)
	verifier := NewJWKSVerifier(serviceConfig)
	identityConfig := NewIdentityConfig(serviceConfig)
	identityUsecases := identity.NewUsecases(verifier, identityConfig)
	handlerFunc := NewAuthMiddleware(logger, serviceConfig, usecases, identityUsecases)
	toolRepository := tool.NewRepository(db)
	adminRepository := admin.NewRepository(db)
	tenantLimitsPort := ProvideToolTenantLimits(adminRepository)
	compilerCache := NewSchemaCache()
	toolUsecases := tool.NewUsecases(toolRepository, tenantLimitsPort, compilerCache)
	handler := ProvideToolHandler(toolUsecases)
	policyRepository := policy.NewRepository(db)
	toolLookupPort := ProvidePolicyToolLookup(toolUsecases)
	policyUsecases := policy.NewUsecases(policyRepository, toolLookupPort)
	policyUsecase := policy.AsPolicyUsecase(policyUsecases)
	policyHandler := policy.NewHandler(policyUsecase)
	auditRepository := audit.NewRepository(db)
	auditUsecases := audit.NewUsecases(auditRepository)
	auditUsecase := audit.AsAuditUsecase(auditUsecases)
	auditHandler := audit.NewHandler(auditUsecase)
	toolRepoPort := ProvideGatewayToolRepo(toolRepository)
	policyRepoPort := ProvideGatewayPolicyRepo(policyRepository)
	auditRepoPort := ProvideGatewayAuditRepo(auditRepository)
	aesgcm, err := NewMasterCrypto(serviceConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	secretsRepository := secrets.NewRepository(db, aesgcm)
	secretRepoPort := ProvideGatewaySecretRepo(secretsRepository)
	egressRepository := egress.NewRepository(db)
	egressToolLookupPort := ProvideEgressToolLookup(toolUsecases)
	egressUsecases := egress.NewUsecases(egressRepository, egressToolLookupPort)
	egressPort := ProvideGatewayEgressPort(egressUsecases)
	adapter, cleanup2, err := NewRateLimiter(serviceConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rateLimiterPort := ProvideGatewayRateLimiter(adapter)
	executor := NewHTTPExecutor(serviceConfig)
	httpExecutorPort := ProvideGatewayHTTPExecutor(executor)
	idempotencyRepository := gateway.NewIdempotencyRepository(db)
	idempotencyPort := ProvideGatewayIdempotencyRepo(idempotencyRepository)
	gatewayTenantLimitsPort := ProvideGatewayTenantCaps(adminRepository)
	actionoverridesRepository := actionoverrides.NewRepository()
	protectedResourcePort := ProvideGatewayProtectedResources(adminRepository)
	restoreEvidencePort := ProvideGatewayRestoreEvidence(adminRepository)
	intentRepository := gateway.NewIntentRepository(db)
	intentRepoPort := ProvideGatewayIntentRepo(intentRepository)
	leaseRepository := gateway.NewLeaseRepository(db)
	leaseRepoPort := ProvideGatewayLeaseRepo(leaseRepository)
	gatewayConfig := ProvideGatewayConfig(serviceConfig)
	leaseMetadataBroker := gateway.NewLeaseMetadataBroker(gatewayConfig)
	leaseCredentialBrokerPort := ProvideGatewayLeaseCredentialBroker(leaseMetadataBroker)
	approvalRepository := approval.NewRepository(db)
	intentStatusPort := ProvideApprovalIntentStatusPort(intentRepository)
	approvalUsecases := ProvideApprovalUsecases(approvalRepository, intentStatusPort, auditRepository)
	gatewayAdapter := approval.NewGatewayAdapter(approvalUsecases)
	approvalPort := ProvideGatewayApprovalPort(gatewayAdapter)
	runMetrics := telemetry.NewRunMetrics()
	runMetricsPort := ProvideGatewayMetrics(runMetrics)
	evaluator := policy.NewEvaluator()
	detector := NewDLPDetector()
	gatewayUsecases := ProvideGatewayUsecases(toolRepoPort, policyRepoPort, auditRepoPort, secretRepoPort, egressPort, rateLimiterPort, httpExecutorPort, idempotencyPort, gatewayTenantLimitsPort, actionoverridesRepository, protectedResourcePort, restoreEvidencePort, intentRepoPort, leaseRepoPort, leaseCredentialBrokerPort, approvalPort, runMetricsPort, compilerCache, evaluator, detector, gatewayConfig, logger)
	gatewayHandler := ProvideGatewayHandler(gatewayUsecases)
	secretsToolLookupPort := ProvideSecretsToolLookup(toolUsecases)
	secretsUsecases := secrets.NewUsecases(secretsRepository, secretsToolLookupPort)
	secretsUsecase := secrets.AsSecretsUsecase(secretsUsecases)
	secretsHandler := secrets.NewHandler(secretsUsecase)
	egressUsecase := egress.AsEgressUsecase(egressUsecases)
	egressHandler := egress.NewHandler(egressUsecase)
	toolPort := ProvideMCPToolPort(toolUsecases)
	runPort := ProvideMCPRunPort(gatewayUsecases)
	mcpUsecases := mcp.NewUsecases(toolPort, runPort)
	mcpUsecase := mcp.AsMCPUsecase(mcpUsecases)
	mcpHandler := mcp.NewHandler(mcpUsecase)
	a2aRunPort := ProvideA2ARunPort(gatewayUsecases)
	a2aUsecases := a2a.NewUsecases(a2aRunPort)
	a2aUsecase := a2a.AsA2AUsecase(a2aUsecases)
	a2aHandler := a2a.NewHandler(a2aUsecase)
	oidcConfig := NewOIDCConfig(serviceConfig)
	discoveryClient := NewOIDCDiscoveryClient(oidcConfig)
	tokenExchanger := NewOIDCTokenExchanger(oidcConfig, discoveryClient)
	oidcHandler := NewOIDCHandler(oidcConfig, discoveryClient, tokenExchanger, identityUsecases)
	approvalHandler := approval.NewHandler(approvalUsecases)
	orgHandler := org.NewHandler(repository)
	usagemeteringRepository := usagemetering.NewRepository(db)
	apiCallsMiddlewareFunc := usagemetering.NewAPICallsMiddleware(usagemeteringRepository)
	engine := NewRouter(db, logger, serviceConfig, httpServerConfig, handlerFunc, handler, policyHandler, auditHandler, gatewayHandler, secretsHandler, egressHandler, mcpHandler, a2aHandler, oidcHandler, approvalHandler, orgHandler, apiCallsMiddlewareFunc)
	apiConfig := ProvideAPIConfig(cfg)
	server := NewHTTPServer(apiConfig, engine)
	app := NewApp(engine, server)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
