FROM golang:1.26-alpine

RUN apk add --no-cache git wget
RUN GOBIN=/usr/local/bin go install github.com/air-verse/air@v1.61.7

WORKDIR /workspace/nexus/governance

COPY nexus/governance/go.mod nexus/governance/go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
