import { useQuery } from '@tanstack/react-query';

import { getIncidents } from '../lib/api';

export default function IncidentsPage() {
  const query = useQuery({
    queryKey: ['incidents'],
    queryFn: () => getIncidents(200),
    refetchInterval: 10000,
  });

  return (
    <div className="panel-page">
      <h2>Incidents</h2>
      <p className="muted">Operational incidents generated by operators and analysts.</p>

      {query.isLoading && <p className="muted">Loading incidents...</p>}

      <table className="table">
        <thead>
          <tr>
            <th>Severity</th>
            <th>Status</th>
            <th>Title</th>
            <th>Opened</th>
            <th>Summary</th>
          </tr>
        </thead>
        <tbody>
          {(query.data?.items ?? []).map((incident) => (
            <tr key={incident.id}>
              <td>{incident.severity}</td>
              <td>{incident.status}</td>
              <td>{incident.title}</td>
              <td>{new Date(incident.opened_at).toLocaleString()}</td>
              <td>{incident.summary}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

