package types

const (
	ErrCodeUnauthorized        = "UNAUTHORIZED"
	ErrCodeNotFound            = "NOT_FOUND"
	ErrCodeValidation          = "VALIDATION_ERROR"
	ErrCodeSchemaInvalid       = "SCHEMA_INVALID"
	ErrCodePolicyDenied        = "POLICY_DENIED"
	ErrCodeRateLimited         = "RATE_LIMITED"
	ErrCodeUpstream5xx         = "UPSTREAM_5XX"
	ErrCodeNetworkError        = "NETWORK_ERROR"
	ErrCodeTimeout             = "TIMEOUT"
	ErrCodeResponseTooLarge    = "RESPONSE_TOO_LARGE"
	ErrCodeOutputSchemaInvalid = "OUTPUT_SCHEMA_INVALID"
	ErrCodeInvalidGETInput     = "INVALID_GET_INPUT"
	ErrCodeEgressDenied        = "EGRESS_DENIED"
	ErrCodeDLPDenied           = "DLP_DENIED"
	ErrCodeSecretDenied        = "SECRET_ACCESS_DENIED"
	ErrCodeSecretNotFound      = "SECRET_NOT_FOUND"
	ErrCodeCryptoFailed        = "CRYPTO_FAILED"
	ErrCodeIdempotencyRequired = "IDEMPOTENCY_REQUIRED"
	ErrCodeIdempotencyConflict = "IDEMPOTENCY_KEY_CONFLICT"
	ErrCodeIdempotencyProgress = "IDEMPOTENCY_IN_PROGRESS"
	ErrCodeIdempotencyStore    = "IDEMPOTENCY_STORE_ERROR"
	ErrCodeTimeoutBudget       = "TIMEOUT_BUDGET_EXCEEDED"
	ErrCodeExportFormatInvalid = "EXPORT_FORMAT_INVALID"
	ErrCodeExportRangeInvalid  = "EXPORT_RANGE_INVALID"
	ErrCodeToolClassInvalid    = "TOOL_CLASSIFICATION_INVALID"
	ErrCodeToolSensitivity     = "TOOL_SENSITIVITY_INVALID"
	ErrCodeInternal            = "INTERNAL"
)
