// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"nexus-saas/cmd/config"
	"nexus-saas/internal/actions"
	"nexus-saas/internal/admin"
	"nexus-saas/internal/alerts"
	"nexus-saas/internal/assistant"
	"nexus-saas/internal/clerkwebhook"
	"nexus-saas/internal/contracts"
	"nexus-saas/internal/coreproxy"
	"nexus-saas/internal/events"
	"nexus-saas/internal/identity"
	"nexus-saas/internal/incidents"
	"nexus-saas/internal/org"
	"nexus-saas/internal/policyproposal"
	"nexus-saas/internal/session"
	"nexus-saas/internal/usagemetering"
	"nexus-saas/internal/users"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*App, func(), error) {
	apiConfig := ProvideAPIConfig(cfg)
	dbConfig := ProvideDBConfig(cfg)
	serviceConfig := ProvideServiceConfig(cfg)
	logger := NewLogger(serviceConfig)
	gormConfig := NewGormConfig(logger)
	db, cleanup, err := NewDB(dbConfig, gormConfig)
	if err != nil {
		return nil, nil, err
	}
	httpServerConfig := ProvideHTTPServerConfig(cfg)
	repository := org.NewRepository(db)
	usecases := org.NewUsecases(repository)
	verifier := NewJWKSVerifier(serviceConfig)
	identityConfig := NewIdentityConfig(serviceConfig)
	identityUsecases := identity.NewUsecases(verifier, identityConfig)
	handlerFunc := NewAuthMiddleware(logger, serviceConfig, usecases, identityUsecases)
	adminRepository := admin.NewRepository(db)
	adminUsecases := admin.NewUsecases(adminRepository)
	handler := admin.NewHandler(adminUsecases)
	eventsRepository := events.NewRepository(db)
	usagemeteringRepository := usagemetering.NewRepository(db)
	meteringPort := ProvideEventsMeteringPort(usagemeteringRepository)
	eventsUsecases := events.NewUsecases(eventsRepository, meteringPort)
	eventsHandler := events.NewHandler(eventsUsecases)
	actionsRepository := actions.NewRepository(db)
	eventSink := ProvideActionsEventSink(eventsUsecases)
	actionsMeteringPort := ProvideActionsMeteringPort(usagemeteringRepository)
	actionsUsecases := actions.NewUsecases(actionsRepository, eventSink, actionsMeteringPort)
	actionsHandler := actions.NewHandler(actionsUsecases)
	incidentsRepository := incidents.NewRepository(db)
	incidentsEventSink := ProvideIncidentsEventSink(eventsUsecases)
	incidentsMeteringPort := ProvideIncidentsMeteringPort(usagemeteringRepository)
	incidentsUsecases := incidents.NewUsecases(incidentsRepository, incidentsEventSink, incidentsMeteringPort)
	incidentsHandler := incidents.NewHandler(incidentsUsecases)
	alertsRepository := alerts.NewRepository(db)
	auditMetricsSource := alerts.NewAuditMetricsSource(db)
	alertsUsecases := alerts.NewUsecases(alertsRepository, auditMetricsSource, logger)
	alertsHandler := alerts.NewHandler(alertsUsecases)
	sessionRepository := session.NewRepository(db)
	sessionUsecases := session.NewUsecases(sessionRepository)
	sessionHandler := session.NewHandler(sessionUsecases)
	policyproposalRepository := policyproposal.NewRepository(db)
	policyproposalEventSink := ProvidePolicyProposalEventSink(eventsUsecases)
	policyproposalUsecases := policyproposal.NewUsecases(policyproposalRepository, policyproposalEventSink)
	policyproposalHandler := policyproposal.NewHandler(policyproposalUsecases)
	assistantConfig := ProvideAssistantConfig()
	assistantUsecases := assistant.NewUsecases(assistantConfig)
	assistantHandler := assistant.NewHandler(assistantUsecases)
	oidcConfig := NewOIDCConfig(serviceConfig)
	discoveryClient := NewOIDCDiscoveryClient(oidcConfig)
	tokenExchanger := NewOIDCTokenExchanger(oidcConfig, discoveryClient)
	oidcHandler := NewOIDCHandler(oidcConfig, discoveryClient, tokenExchanger, identityUsecases)
	orgHandler := org.NewHandler(repository)
	usersRepository := users.NewRepository(db)
	usersUsecases := users.NewUsecases(usersRepository)
	usersHandler := users.NewHandler(usersUsecases)
	clerkwebhookHandler := clerkwebhook.NewHandler(serviceConfig, usersUsecases, logger)
	contractsHandler := contracts.NewHandler(serviceConfig, adminRepository, usagemeteringRepository, eventsUsecases, actionsUsecases)
	coreproxyHandler := coreproxy.NewHandler()
	apiCallsMiddlewareFunc := usagemetering.NewAPICallsMiddleware(usagemeteringRepository)
	engine := NewRouter(db, logger, serviceConfig, httpServerConfig, handlerFunc, handler, eventsHandler, actionsHandler, incidentsHandler, alertsHandler, sessionHandler, policyproposalHandler, assistantHandler, oidcHandler, orgHandler, usersHandler, clerkwebhookHandler, contractsHandler, coreproxyHandler, apiCallsMiddlewareFunc)
	server := NewHTTPServer(apiConfig, engine)
	app := NewApp(server)
	return app, func() {
		cleanup()
	}, nil
}
