// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"nexus-core/cmd/config"
	"nexus-core/internal/a2a"
	"nexus-core/internal/actions"
	"nexus-core/internal/admin"
	"nexus-core/internal/assistant"
	"nexus-core/internal/audit"
	"nexus-core/internal/egress"
	"nexus-core/internal/events"
	"nexus-core/internal/gateway"
	"nexus-core/internal/gateway/executor/telemetry"
	"nexus-core/internal/identity"
	"nexus-core/internal/incidents"
	"nexus-core/internal/mcp"
	"nexus-core/internal/org"
	"nexus-core/internal/policy"
	"nexus-core/internal/policyproposal"
	"nexus-core/internal/secrets"
	"nexus-core/internal/alerts"
	"nexus-core/internal/approval"
	"nexus-core/internal/session"
	"nexus-core/internal/tool"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*App, func(), error) {
	dbConfig := ProvideDBConfig(cfg)
	serviceConfig := ProvideServiceConfig(cfg)
	logger := NewLogger(serviceConfig)
	gormConfig := NewGormConfig(logger)
	db, cleanup, err := NewDB(dbConfig, gormConfig)
	if err != nil {
		return nil, nil, err
	}
	httpServerConfig := ProvideHTTPServerConfig(cfg)
	repository := org.NewRepository(db)
	authUsecase := org.NewUsecases(repository)
	orgHandler := org.NewHandler(repository)
	verifier := NewJWKSVerifier(serviceConfig)
	identityConfig := NewIdentityConfig(serviceConfig)
	service := identity.NewUsecases(verifier, identityConfig)
	handlerFunc := NewAuthMiddleware(logger, serviceConfig, authUsecase, service)
	toolRepository := tool.NewRepository(db)
	adminRepository := admin.NewRepository(db)
	tenantLimitsPort := ProvideToolTenantLimits(adminRepository)
	compilerCache := NewSchemaCache()
	serviceImpl := tool.NewUsecases(toolRepository, tenantLimitsPort, compilerCache)
	handler := tool.NewHandler(serviceImpl)
	policyRepository := policy.NewRepository(db)
	toolLookupPort := ProvidePolicyToolLookup(serviceImpl)
	policyUsecases := policy.NewUsecases(policyRepository, toolLookupPort)
	policyHandler := policy.NewHandler(policyUsecases)
	auditRepository := audit.NewRepository(db)
	auditUsecases := audit.NewUsecases(auditRepository)
	auditHandler := audit.NewHandler(auditUsecases)
	adminService := admin.NewUsecases(adminRepository)
	adminHandler := admin.NewHandler(adminService)
	eventsRepository := events.NewRepository(db)
	eventsUsecases := events.NewUsecases(eventsRepository)
	eventsHandler := events.NewHandler(eventsUsecases)
	actionsRepository := actions.NewRepository(db)
	eventSink := ProvideActionsEventSink(eventsUsecases)
	actionsService := actions.NewUsecases(actionsRepository, eventSink)
	actionsHandler := actions.NewHandler(actionsService)
	incidentsRepository := incidents.NewRepository(db)
	incidentsEventSink := ProvideIncidentsEventSink(eventsUsecases)
	incidentsService := incidents.NewUsecases(incidentsRepository, incidentsEventSink)
	incidentsHandler := incidents.NewHandler(incidentsService)
	policyproposalRepository := policyproposal.NewRepository(db)
	policyproposalEventSink := ProvidePolicyProposalEventSink(eventsUsecases)
	policyproposalService := policyproposal.NewUsecases(policyproposalRepository, policyproposalEventSink)
	policyproposalHandler := policyproposal.NewHandler(policyproposalService)
	assistantConfig := ProvideAssistantConfig()
	assistantService := assistant.NewUsecases(assistantConfig)
	assistantHandler := assistant.NewHandler(assistantService)
	toolRepoPort := ProvideGatewayToolRepo(toolRepository)
	policyRepoPort := ProvideGatewayPolicyRepo(policyRepository)
	auditRepoPort := ProvideGatewayAuditRepo(auditRepository)
	aesgcm, err := NewMasterCrypto(serviceConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	secretsRepository := secrets.NewRepository(db, aesgcm)
	secretRepoPort := ProvideGatewaySecretRepo(secretsRepository)
	egressRepository := egress.NewRepository(db)
	egressToolLookupPort := ProvideEgressToolLookup(serviceImpl)
	egressUsecases := egress.NewUsecases(egressRepository, egressToolLookupPort)
	egressPort := ProvideGatewayEgressPort(egressUsecases)
	adapter, cleanup2, err := NewRateLimiter(serviceConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rateLimiterPort := ProvideGatewayRateLimiter(adapter)
	executor := NewHTTPExecutor(serviceConfig)
	httpExecutorPort := ProvideGatewayHTTPExecutor(executor)
	idempotencyRepository := gateway.NewIdempotencyRepository(db)
	idempotencyPort := ProvideGatewayIdempotencyRepo(idempotencyRepository)
	gatewayTenantLimitsPort := ProvideGatewayTenantCaps(adminRepository)
	actionOverridesPort := ProvideGatewayActionOverrides(actionsService)
	runMetrics := telemetry.NewRunMetrics()
	runMetricsPort := ProvideGatewayMetrics(runMetrics)
	evaluator := policy.NewEvaluator()
	detector := NewDLPDetector()
	gatewayConfig := ProvideGatewayConfig(serviceConfig)
	approvalRepo := approval.NewRepository(db)
	approvalSvc := approval.NewUsecases(approvalRepo)
	approvalAdapter := approval.NewGatewayAdapter(approvalSvc)
	approvalHandler := approval.NewHandler(approvalSvc)
	alertsRepo := alerts.NewRepository(db)
	alertsMetrics := alerts.NewAuditMetricsSource(db)
	alertsSvc := alerts.NewUsecases(alertsRepo, alertsMetrics, logger)
	alertsHandler := alerts.NewHandler(alertsSvc)
	sessionRepo := session.NewRepository(db)
	sessionSvc := session.NewUsecases(sessionRepo)
	sessionHandler := session.NewHandler(sessionSvc)
	gatewayService := gateway.NewUsecases(toolRepoPort, policyRepoPort, auditRepoPort, secretRepoPort, egressPort, rateLimiterPort, httpExecutorPort, idempotencyPort, gatewayTenantLimitsPort, actionOverridesPort, approvalAdapter, runMetricsPort, compilerCache, evaluator, detector, gatewayConfig, logger)
	gatewayHandler := gateway.NewHandler(gatewayService)
	secretsToolLookupPort := ProvideSecretsToolLookup(serviceImpl)
	secretsUsecases := secrets.NewUsecases(secretsRepository, secretsToolLookupPort)
	secretsHandler := secrets.NewHandler(secretsUsecases)
	egressHandler := egress.NewHandler(egressUsecases)
	toolPort := ProvideMCPToolPort(serviceImpl)
	runPort := ProvideMCPRunPort(gatewayService)
	mcpService := mcp.NewUsecases(toolPort, runPort)
	mcpHandler := mcp.NewHandler(mcpService)
	a2aRunPort := ProvideA2ARunPort(gatewayService)
	a2aService := a2a.NewUsecases(a2aRunPort)
	a2aHandler := a2a.NewHandler(a2aService)
	oidcConfig := NewOIDCConfig(serviceConfig)
	discoveryClient := NewOIDCDiscoveryClient(oidcConfig)
	tokenExchanger := NewOIDCTokenExchanger(oidcConfig, discoveryClient)
	oidcHandler := NewOIDCHandler(oidcConfig, discoveryClient, tokenExchanger, service)
	engine := NewRouter(db, logger, serviceConfig, httpServerConfig, handlerFunc, handler, policyHandler, auditHandler, adminHandler, eventsHandler, actionsHandler, incidentsHandler, policyproposalHandler, assistantHandler, gatewayHandler, secretsHandler, egressHandler, mcpHandler, a2aHandler, oidcHandler, approvalHandler, alertsHandler, sessionHandler, orgHandler)
	apiConfig := ProvideAPIConfig(cfg)
	server := NewHTTPServer(apiConfig, engine)
	app := NewApp(engine, server, actionsService)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
