root = "."
tmp_dir = "tmp"

[build]
  cmd = "CGO_ENABLED=0 go build -o ./tmp/nexus ./cmd/api"
  bin = "./tmp/nexus"
  full_bin = "./tmp/nexus"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
