FROM golang:1.24-alpine
RUN apk add --no-cache git wget
RUN GOBIN=/usr/local/bin go install github.com/air-verse/air@v1.61.7
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
EXPOSE 8080
CMD ["sh", "-c", "go run ./cmd/migrate -cmd up && air -c .air.toml"]
