FROM golang:1.25-alpine
RUN apk add --no-cache git wget
RUN GOBIN=/usr/local/bin go install github.com/air-verse/air@v1.61.7
WORKDIR /src
COPY control-workers/go.mod control-workers/go.sum ./control-workers/
COPY pkgs/go-pkg ./pkgs/go-pkg
WORKDIR /src/control-workers
RUN go mod download
EXPOSE 8090
CMD ["air", "-c", ".air.toml"]
