FROM golang:1.24-alpine
RUN apk add --no-cache git wget
RUN GOBIN=/usr/local/bin go install github.com/air-verse/air@v1.61.7
WORKDIR /src
COPY nexus-control-operators/go.mod nexus-control-operators/go.sum ./nexus-control-operators/
COPY pkgs/go-pkg ./pkgs/go-pkg
WORKDIR /src/nexus-control-operators
RUN go mod download
EXPOSE 8082
CMD ["air", "-c", ".air.toml"]
