// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"nexus-gateway/cmd/config"
	"nexus-gateway/internal/audit"
	"nexus-gateway/internal/gateway"
	"nexus-gateway/internal/org"
	"nexus-gateway/internal/policy"
	"nexus-gateway/internal/tool"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*App, func(), error) {
	dbConfig := ProvideDBConfig(cfg)
	serviceConfig := ProvideServiceConfig(cfg)
	logger := NewLogger(serviceConfig)
	gormConfig := NewGormConfig(logger)
	db, cleanup, err := NewDB(dbConfig, gormConfig)
	if err != nil {
		return nil, nil, err
	}
	httpServerConfig := ProvideHTTPServerConfig(cfg)
	repository := org.NewRepository(db)
	authUsecase := org.NewAuthUsecase(repository)
	handlerFunc := NewAuthMiddleware(logger, authUsecase)
	toolRepository := tool.NewRepository(db)
	compilerCache := NewSchemaCache()
	serviceImpl := tool.NewService(toolRepository, compilerCache)
	handler := tool.NewHandler(serviceImpl)
	policyRepository := policy.NewRepository(db)
	toolLookupPort := ProvidePolicyToolLookup(serviceImpl)
	service := policy.NewService(policyRepository, toolLookupPort)
	policyHandler := policy.NewHandler(service)
	auditRepository := audit.NewRepository(db)
	auditService := audit.NewService(auditRepository)
	auditHandler := audit.NewHandler(auditService)
	toolRepoPort := ProvideGatewayToolRepo(toolRepository)
	policyRepoPort := ProvideGatewayPolicyRepo(policyRepository)
	auditRepoPort := ProvideGatewayAuditRepo(auditRepository)
	limiter := NewRateLimiter()
	rateLimiterPort := ProvideGatewayRateLimiter(limiter)
	executor := NewHTTPExecutor(serviceConfig)
	httpExecutorPort := ProvideGatewayHTTPExecutor(executor)
	evaluator := policy.NewEvaluator()
	gatewayConfig := ProvideGatewayConfig(serviceConfig)
	gatewayService := gateway.NewService(toolRepoPort, policyRepoPort, auditRepoPort, rateLimiterPort, httpExecutorPort, compilerCache, evaluator, gatewayConfig, logger)
	gatewayHandler := gateway.NewHandler(gatewayService)
	engine := NewRouter(db, logger, serviceConfig, httpServerConfig, handlerFunc, handler, policyHandler, auditHandler, gatewayHandler)
	apiConfig := ProvideAPIConfig(cfg)
	server := NewHTTPServer(apiConfig, engine)
	app := NewApp(engine, server)
	return app, func() {
		cleanup()
	}, nil
}
