// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"nexus-gateway/cmd/config"
	"nexus-gateway/internal/a2a"
	"nexus-gateway/internal/admin"
	"nexus-gateway/internal/audit"
	"nexus-gateway/internal/egress"
	"nexus-gateway/internal/gateway"
	"nexus-gateway/internal/gateway/executor/telemetry"
	"nexus-gateway/internal/identity"
	"nexus-gateway/internal/mcp"
	"nexus-gateway/internal/org"
	"nexus-gateway/internal/policy"
	"nexus-gateway/internal/secrets"
	"nexus-gateway/internal/tool"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*App, func(), error) {
	dbConfig := ProvideDBConfig(cfg)
	serviceConfig := ProvideServiceConfig(cfg)
	logger := NewLogger(serviceConfig)
	gormConfig := NewGormConfig(logger)
	db, cleanup, err := NewDB(dbConfig, gormConfig)
	if err != nil {
		return nil, nil, err
	}
	httpServerConfig := ProvideHTTPServerConfig(cfg)
	repository := org.NewRepository(db)
	authUsecase := org.NewAuthUsecase(repository)
	verifier := NewJWKSVerifier(serviceConfig)
	identityConfig := NewIdentityConfig(serviceConfig)
	service := identity.NewService(verifier, identityConfig)
	handlerFunc := NewAuthMiddleware(logger, serviceConfig, authUsecase, service)
	toolRepository := tool.NewRepository(db)
	adminRepository := admin.NewRepository(db)
	tenantLimitsPort := ProvideToolTenantLimits(adminRepository)
	compilerCache := NewSchemaCache()
	serviceImpl := tool.NewService(toolRepository, tenantLimitsPort, compilerCache)
	handler := tool.NewHandler(serviceImpl)
	policyRepository := policy.NewRepository(db)
	toolLookupPort := ProvidePolicyToolLookup(serviceImpl)
	policyService := policy.NewService(policyRepository, toolLookupPort)
	policyHandler := policy.NewHandler(policyService)
	auditRepository := audit.NewRepository(db)
	auditService := audit.NewService(auditRepository)
	auditHandler := audit.NewHandler(auditService)
	adminService := admin.NewService(adminRepository)
	adminHandler := admin.NewHandler(adminService)
	toolRepoPort := ProvideGatewayToolRepo(toolRepository)
	policyRepoPort := ProvideGatewayPolicyRepo(policyRepository)
	auditRepoPort := ProvideGatewayAuditRepo(auditRepository)
	aesgcm, err := NewMasterCrypto(serviceConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	secretsRepository := secrets.NewRepository(db, aesgcm)
	secretRepoPort := ProvideGatewaySecretRepo(secretsRepository)
	egressRepository := egress.NewRepository(db)
	egressToolLookupPort := ProvideEgressToolLookup(serviceImpl)
	egressService := egress.NewService(egressRepository, egressToolLookupPort)
	egressPort := ProvideGatewayEgressPort(egressService)
	adapter, cleanup2, err := NewRateLimiter(serviceConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rateLimiterPort := ProvideGatewayRateLimiter(adapter)
	executor := NewHTTPExecutor(serviceConfig)
	httpExecutorPort := ProvideGatewayHTTPExecutor(executor)
	idempotencyRepository := gateway.NewIdempotencyRepository(db)
	idempotencyPort := ProvideGatewayIdempotencyRepo(idempotencyRepository)
	gatewayTenantLimitsPort := ProvideGatewayTenantCaps(adminRepository)
	runMetrics := telemetry.NewRunMetrics()
	runMetricsPort := ProvideGatewayMetrics(runMetrics)
	evaluator := policy.NewEvaluator()
	detector := NewDLPDetector()
	gatewayConfig := ProvideGatewayConfig(serviceConfig)
	gatewayService := gateway.NewService(toolRepoPort, policyRepoPort, auditRepoPort, secretRepoPort, egressPort, rateLimiterPort, httpExecutorPort, idempotencyPort, gatewayTenantLimitsPort, runMetricsPort, compilerCache, evaluator, detector, gatewayConfig, logger)
	gatewayHandler := gateway.NewHandler(gatewayService)
	secretsToolLookupPort := ProvideSecretsToolLookup(serviceImpl)
	secretsService := secrets.NewService(secretsRepository, secretsToolLookupPort)
	secretsHandler := secrets.NewHandler(secretsService)
	egressHandler := egress.NewHandler(egressService)
	toolPort := ProvideMCPToolPort(serviceImpl)
	runPort := ProvideMCPRunPort(gatewayService)
	mcpService := mcp.NewService(toolPort, runPort)
	mcpHandler := mcp.NewHandler(mcpService)
	a2aRunPort := ProvideA2ARunPort(gatewayService)
	a2aService := a2a.NewService(a2aRunPort)
	a2aHandler := a2a.NewHandler(a2aService)
	engine := NewRouter(db, logger, serviceConfig, httpServerConfig, handlerFunc, handler, policyHandler, auditHandler, adminHandler, gatewayHandler, secretsHandler, egressHandler, mcpHandler, a2aHandler)
	apiConfig := ProvideAPIConfig(cfg)
	server := NewHTTPServer(apiConfig, engine)
	app := NewApp(engine, server)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
