FROM golang:1.26-alpine

RUN apk add --no-cache git wget
RUN GOBIN=/usr/local/bin go install github.com/air-verse/air@v1.61.7

WORKDIR /src

COPY control-plane/go.mod control-plane/go.sum ./control-plane/
COPY pkgs/go-pkg/go.mod pkgs/go-pkg/go.sum ./pkgs/go-pkg/
WORKDIR /src/control-plane
RUN go mod download

WORKDIR /src/control-plane

EXPOSE 8081

CMD ["air", "-c", ".air.toml"]
